# 幫這個 action 取個名字，會在 action 頁面的左側顯示
name: Telegram Notification Push

# 要在什麼時候觸發，實測只設定 push 沒有限定更細的 type 或條件時，
# 新增 tag、設定 release 等活動都會觸發
on:
  push
  #release:
  # types: [published]
  
# 設定 job 的內容
jobs:

  SentMessageToTelegram:
    runs-on: ubuntu-latest
    steps:
      - env:
          SECRETSID: ${{ vars.ID }}
          SECRETSTOKEN: ${{ secrets.TOKEN }}
        run: curl -X POST "https://api.telegram.org/bot${SECRETSTOKEN}/sendMessage" -d "chat_id=${SECRETSID}&text=不用上班的程序员2"
